<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thông tin liên hệ</title>
</head>
<body>
    <h3>Thông tin liên hệ</h3>
    <div>
        <p style="font-size: 17px">- Họ và tên: <b><?=$this->name?></b></p>
        <p style="font-size: 17px">- Số ĐT: <b><?=$this->phone?></b></p>
        <p style="font-size: 17px">- Email: <b><?=$this->email?></b></p>
        <p style="font-size: 17px">- Nội dung: <br><br><?=$this->content?></p>
    </div>
</body>
</html>